SELECT DISTINCT
d.ID,
d.EMAIL,
d.FIRST_NAME,
d.LAST_NAME
FROM
DEVELOPERS  as d
LEFT OUTER JOIN SKILLCODES  as s
ON (d.SKILL_CODE % (s.CODE * 2)) >= s.CODE
WHERE
s.NAME = 'Python'
OR s.NAME = 'C#'
ORDER BY 1;